In [1]:
# Required modules

import numpy as np
import pandas as pd
import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [2]:
# Load the data
# data = pd.read_csv("/content/drive/MyDrive/Appendix 2 EN Steels.csv")
data = pd.read_csv("Appendix 2 EN Steels.csv")
data.head()

Sl. No.     C    Si    Mn      P    Ni  ...   TT   YS   UTS    EL    RA  IS
0        1  0.32  0.23  1.28  0.028  0.85  ...  580  934  1019  18.0  54.0  35
1        2  0.32  0.23  1.28  0.028  0.85  ...  620  736   845  22.0  59.0  42
2        3  0.33  0.19  1.45  0.026  0.89  ...  605  785   888  21.0  60.0  72
3        4  0.33  0.19  1.45  0.026  0.89  ...  625  693   824  21.5  57.0  43
4        5  0.35  0.19  1.50  0.026  0.93  ...  650  681   839  21.5  58.0  89

[5 rows x 16 columns]

In [3]:
# Inspecting the data

data.info()
data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140 entries, 0 to 139
Data columns (total 16 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Sl. No.  140 non-null    int64  
 1   C        140 non-null    float64
 2   Si       140 non-null    float64
 3   Mn       140 non-null    float64
 4   P        140 non-null    float64
 5   Ni       140 non-null    float64
 6   Cr       140 non-null    float64
 7   Mo       140 non-null    float64
 8   Mn/S     140 non-null    int64  
 9   CR       140 non-null    int64  
 10  TT       140 non-null    int64  
 11  YS       140 non-null    int64  
 12  UTS      140 non-null    int64  
 13  EL       140 non-null    float64
 14  RA       140 non-null    float64
 15  IS       140 non-null    int64  
dtypes: float64(9), int64(7)
memory usage: 17.6 KB


Sl. No.           C          Si  ...          EL          RA          IS
count  140.0000  140.000000  140.000000  ...  140.000000  140.000000  140.000000
mean    70.5000    0.374929    0.264643  ...   21.160714   56.342857   57.564286
std     40.5586    0.030429    0.045824  ...    3.426656    6.460195   21.887288
min      1.0000    0.320000    0.190000  ...   13.000000   31.000000   15.000000
25%     35.7500    0.350000    0.250000  ...   18.500000   52.500000   42.000000
50%     70.5000    0.360000    0.250000  ...   21.000000   57.000000   60.000000
75%    105.2500    0.400000    0.300000  ...   23.625000   61.500000   75.000000
max    140.0000    0.440000    0.370000  ...   29.000000   67.500000   94.000000

[8 rows x 16 columns]

In [4]:
#create a dataframe with all training data except the target column
X = data[['C', 'Si', 'Mn', 'P', 'Ni', 'Cr', 'Mo', 'Mn/S', 'CR', 'TT']]
# X = df.drop(columns=['YS', 'UTS', 'EL', 'RA', 'IS'])

# X.dtypes

In [5]:
#create a dataframe with all training data except the target column
Y = data[['YS', 'UTS', 'EL', 'RA', 'IS']]

#check that the target variable has been removed
# Y.head()

In [6]:
# Scaling the data

X_scale = MinMaxScaler()
y_scale = MinMaxScaler()

X_scaled = X_scale.fit_transform(X)
y_scaled = y_scale.fit_transform(Y)

In [7]:
# Train and Test split using scaled data

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_scaled, train_size=0.80)

# Train and Test split using without scaled data

# X_train, X_test, y_train, y_test = train_test_split(X, Y, train_size=0.80)
# print(X_train.shape)
# print(y_train.shape)
# print(X_test.shape)
# print(y_test.shape)

In [8]:
# Model Definition

modelSL = tf.keras.models.Sequential([
    tf.keras.layers.Dense(10, activation='sigmoid'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(8, activation='sigmoid'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(5, activation='linear')
])


model2L = tf.keras.models.Sequential([
    tf.keras.layers.Dense(10, activation='sigmoid'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(11, activation='sigmoid'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(11, activation='sigmoid'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(5, activation='linear')
])

In [9]:
# Custom loss

def rmse(y_true, y_pred):
    return tf.math.sqrt(tf.keras.losses.mean_squared_error(y_true, y_pred))

In [10]:
# optimizer for SL and loss function
optimsl = tf.keras.optimizers.SGD(learning_rate=0.25, momentum=0.9)
loss = tf.keras.losses.mean_squared_error

In [11]:
# compile model using mse as a measure of modelSL performance

modelSL.compile(optimizer=optimsl, loss=loss, metrics = [rmse])

In [12]:
# Fitting the modelSL

modelSL.fit(X_train, y_train, epochs=1000)

Epoch 1/1000
4/4 [==============================] - 3s 5ms/step - loss: 0.3779 - rmse: 0.5763
Epoch 2/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.2612 - rmse: 0.4801
Epoch 3/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.0875 - rmse: 0.2774
Epoch 4/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.0732 - rmse: 0.2565
Epoch 5/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.0591 - rmse: 0.2241
Epoch 6/1000
4/4 [==============================] - 0s 5ms/step - loss: 0.0580 - rmse: 0.2238
Epoch 7/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.0506 - rmse: 0.2043
Epoch 8/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.0507 - rmse: 0.2053
Epoch 9/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.0479 - rmse: 0.1967
Epoch 10/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.0486 - rmse: 0.1996
Epoch 11/1000
4/4 [==============================] - 0s 7ms

In [13]:
# optimizer for 2L
optim2l = tf.keras.optimizers.SGD(learning_rate=0.55, momentum=0.65)

In [14]:
# compile model using mse as a measure of model2L performance

model2L.compile(optimizer=optim2l, loss=loss, metrics = [rmse])

In [15]:
# Fitting the model2L

model2L.fit(X_train, y_train, epochs=1000)

Epoch 1/1000
4/4 [==============================] - 1s 7ms/step - loss: 0.5598 - rmse: 0.6835
Epoch 2/1000
4/4 [==============================] - 0s 7ms/step - loss: 0.1467 - rmse: 0.3584
Epoch 3/1000
4/4 [==============================] - 0s 7ms/step - loss: 0.0798 - rmse: 0.2647
Epoch 4/1000
4/4 [==============================] - 0s 7ms/step - loss: 0.0598 - rmse: 0.2239
Epoch 5/1000
4/4 [==============================] - 0s 6ms/step - loss: 0.0543 - rmse: 0.2132
Epoch 6/1000
4/4 [==============================] - 0s 6ms/step - loss: 0.0486 - rmse: 0.2006
Epoch 7/1000
4/4 [==============================] - 0s 6ms/step - loss: 0.0505 - rmse: 0.2052
Epoch 8/1000
4/4 [==============================] - 0s 7ms/step - loss: 0.0485 - rmse: 0.2011
Epoch 9/1000
4/4 [==============================] - 0s 6ms/step - loss: 0.0483 - rmse: 0.1958
Epoch 10/1000
4/4 [==============================] - 0s 5ms/step - loss: 0.0472 - rmse: 0.1967
Epoch 11/1000
4/4 [==============================] - 0s 8ms

In [16]:
train_pred = modelSL.predict(X_train)
train_pred[:, 0]
y_train[:, 0]

array([0.14746544, 0.58525346, 0.55760369, 0.64208909, 0.59754224,
       0.41781874, 0.11827957, 0.95238095, 0.37173579, 0.12288786,
       0.75883257, 0.55760369, 0.78187404, 0.33333333, 0.12596006,
       0.50230415, 0.29646697, 0.65130568, 0.08141321, 0.56989247,
       0.61136713, 0.33640553, 0.87096774, 0.42703533, 0.26420891,
       0.7265745 , 0.3609831 , 0.3609831 , 0.39016897, 0.22887865,
       0.39938556, 0.67895545, 0.47158218, 0.67281106, 0.12749616,
       0.43164363, 0.31029186, 0.44393241, 0.38095238, 0.31797235,
       0.40552995, 0.30568356, 0.15668203, 0.53149002, 0.29339478,
       0.33794163, 0.52995392, 0.30875576, 0.1812596 , 0.05529954,
       0.22887865, 0.04915515, 0.0952381 , 0.        , 0.06912442,
       0.25960061, 0.51766513, 0.21658986, 0.37634409, 0.64669739,
       0.4546851 , 0.23041475, 0.33333333, 0.84792627, 0.61443932,
       0.35637481, 1.        , 0.48387097, 0.33333333, 0.28725038,
       0.56682028, 0.83870968, 0.32718894, 0.38095238, 0.28725

In [17]:
# finding the mean

np.mean(loss(train_pred, y_train))

0.04396656619771401

In [18]:
# Etr formula to each machenical properties

def etr(actual, predicted):
    return np.mean(np.abs(actual, predicted))

In [19]:
# Summary

modelSL.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                110       
_________________________________________________________________
dropout (Dropout)            (None, 10)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 88        
_________________________________________________________________
dropout_1 (Dropout)          (None, 8)                 0         
_________________________________________________________________
dense_2 (Dense)              (None, 5)                 45        
Total params: 243
Trainable params: 243
Non-trainable params: 0
_________________________________________________________________


In [71]:
# taking one row of test dataset

X_test[0].reshape(1, -1).shape

(1, 10)

In [57]:
# Predictions

predicted = modelSL.predict(X_test[0].reshape(1, -1))
pd.DataFrame(columns=['YS', 'UTS', 'EL', 'RA', 'IS'], data=predicted)

YS       UTS        EL        RA        IS
0  0.407823  0.376355  0.519123  0.717272  0.559071

In [72]:
# input from UI

# input = np.array([[0.32],	[0.23],	[1.28],	[0.028],	[0.85],	[0.46],	[0.16],	[38],	[38],	[580]])
input = np.array([[0.32,	0.23,	1.28,	0.028,	0.85,	0.46,	0.16,	38,	38,	580]])

In [73]:
# Scaling the input values from UI

input_scale = MinMaxScaler()

input_scaled = input_scale.fit_transform(input)
input_scaled.shape

(1, 10)

In [74]:
# prediction with input values from UI
output_predicted = modelSL.predict(input_scaled)
pd.DataFrame(columns=['YS', 'UTS', 'EL', 'RA', 'IS'], data=output_predicted)

YS       UTS        EL        RA        IS
0  0.406864  0.375268  0.519745  0.718418  0.558452

In [76]:
# convert predicted values to its original states show we can compare our model working for UI

y_scale.inverse_transform(output_predicted)

array([[807.86847 , 927.65784 ,  21.315916,  57.22226 ,  59.117702]],
      dtype=float32)

In [47]:
# convert predicted values to its original states show we can campare our model working

y_scale.inverse_transform(predicted)

array([[808.49304 , 928.29694 ,  21.305975,  57.180412,  59.166626]],
      dtype=float32)

In [23]:
# Saving the model single layer

modelSL.save_weights('modelSL.hdf5')

In [24]:
# Saving the model double layer

model2L.save_weights('model2L.hdf5')

In [25]:
# loading the model single layer

modelSL.load_weights('modelSL.hdf5')

In [26]:
# loading the model double layer

model2L.load_weights('model2L.hdf5')