In [1]:
# Required modules

import numpy as np
import pandas as pd
import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

2021-07-18 19:01:36.816838: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-07-18 19:01:36.817016: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
# Load the data
# data = pd.read_csv("/content/drive/MyDrive/Appendix 2 EN Steels.csv")
data = pd.read_csv("Appendix 2 EN Steels.csv")
data.head()

Sl. No.     C    Si    Mn      P    Ni    Cr    Mo  Mn/S  CR   TT   YS  \
0        1  0.32  0.23  1.28  0.028  0.85  0.46  0.16    38  38  580  934   
1        2  0.32  0.23  1.28  0.028  0.85  0.46  0.16    38  16  620  736   
2        3  0.33  0.19  1.45  0.026  0.89  0.56  0.12    73  16  605  785   
3        4  0.33  0.19  1.45  0.026  0.89  0.56  0.12    73   7  625  693   
4        5  0.35  0.19  1.50  0.026  0.93  0.57  0.18    75   7  650  681   

    UTS    EL    RA  IS  
0  1019  18.0  54.0  35  
1   845  22.0  59.0  42  
2   888  21.0  60.0  72  
3   824  21.5  57.0  43  
4   839  21.5  58.0  89

In [3]:
# Inspecting the data

data.info()
data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140 entries, 0 to 139
Data columns (total 16 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Sl. No.  140 non-null    int64  
 1   C        140 non-null    float64
 2   Si       140 non-null    float64
 3   Mn       140 non-null    float64
 4   P        140 non-null    float64
 5   Ni       140 non-null    float64
 6   Cr       140 non-null    float64
 7   Mo       140 non-null    float64
 8   Mn/S     140 non-null    int64  
 9   CR       140 non-null    int64  
 10  TT       140 non-null    int64  
 11  YS       140 non-null    int64  
 12  UTS      140 non-null    int64  
 13  EL       140 non-null    float64
 14  RA       140 non-null    float64
 15  IS       140 non-null    int64  
dtypes: float64(9), int64(7)
memory usage: 17.6 KB


Sl. No.           C          Si          Mn           P          Ni  \
count  140.0000  140.000000  140.000000  140.000000  140.000000  140.000000   
mean    70.5000    0.374929    0.264643    0.984143    0.030721    0.819143   
std     40.5586    0.030429    0.045824    0.509700    0.005088    0.129673   
min      1.0000    0.320000    0.190000    0.330000    0.020000    0.560000   
25%     35.7500    0.350000    0.250000    0.330000    0.030000    0.740000   
50%     70.5000    0.360000    0.250000    1.260000    0.032000    0.890000   
75%    105.2500    0.400000    0.300000    1.400000    0.034000    0.910000   
max    140.0000    0.440000    0.370000    1.510000    0.038000    1.080000   

               Cr          Mo        Mn/S          CR          TT  \
count  140.000000  140.000000  140.000000  140.000000  140.000000   
mean     0.437357    0.173500   36.614286   24.850000  589.571429   
std      0.081423    0.031278   25.803236   27.747299   67.053843   
min      0.210000    0.110000    8.000000    3.000000  400.000000   
25%      0.430000    0.150000    8.000000    7.000000  550.000000   
50%      0.430000    0.160000   40.000000   12.000000  600.000000   
75%      0.490000    0.200000   49.000000   38.000000  642.500000   
max      0.570000    0.250000   86.000000  118.000000  700.000000   

                YS          UTS          EL          RA          IS  
count   140.000000   140.000000  140.000000  140.000000  140.000000  
mean    808.678571   933.300000   21.160714   56.342857   57.564286  
std     150.265150   127.840768    3.426656    6.460195   21.887288  
min     543.000000   707.000000   13.000000   31.000000   15.000000  
25%     692.000000   839.000000   18.500000   52.500000   42.000000  
50%     789.500000   912.000000   21.000000   57.000000   60.000000  
75%     914.000000  1019.000000   23.625000   61.500000   75.000000  
max    1194.000000  1295.000000   29.000000   67.500000   94.000000

In [4]:
#create a dataframe with all training data except the target column
X = data[['C', 'Si', 'Mn', 'P', 'Ni', 'Cr', 'Mo', 'Mn/S', 'CR', 'TT']]
# X = df.drop(columns=['YS', 'UTS', 'EL', 'RA', 'IS'])

# X.dtypes

In [5]:
#create a dataframe with all training data except the target column
Y = data[['YS', 'UTS', 'EL', 'RA', 'IS']]

#check that the target variable has been removed
# Y.head()

In [6]:
# Scaling the data

X_scale = MinMaxScaler()
y_scale = MinMaxScaler()

X_scaled = X_scale.fit_transform(X)
y_scaled = y_scale.fit_transform(Y)

In [7]:
# Train and Test split using scaled data

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_scaled, train_size=0.80)

# Train and Test split using without scaled data

# X_train, X_test, y_train, y_test = train_test_split(X, Y, train_size=0.80)
# print(X_train.shape)
# print(y_train.shape)
# print(X_test.shape)
# print(y_test.shape)

In [8]:
# Model Definition

modelSL = tf.keras.models.Sequential([
    tf.keras.layers.Dense(10, activation='sigmoid'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(8, activation='sigmoid'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(5, activation='linear')
])


model2L = tf.keras.models.Sequential([
    tf.keras.layers.Dense(10, activation='sigmoid'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(11, activation='sigmoid'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(11, activation='sigmoid'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(5, activation='linear')
])

2021-07-18 19:02:19.816006: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2021-07-18 19:02:20.111019: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_SYSTEM_DRIVER_MISMATCH: system has unsupported display driver / cuda driver combination
2021-07-18 19:02:20.111087: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: Inspiron-3542
2021-07-18 19:02:20.111106: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: Inspiron-3542
2021-07-18 19:02:20.111286: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 470.42.1
2021-07-18 19:02:20.111339: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 340.108.0
2021-07-18 19:02:20.111354: E tensorflow/stream_executor/cuda/cuda_diagnostics.cc:313] kernel version 340.108.0 does not match DSO version 470.4

In [9]:
# Custom loss

def rmse(y_true, y_pred):
    return tf.math.sqrt(tf.keras.losses.mean_squared_error(y_true, y_pred))

In [10]:
# optimizer for SL and loss function
optimsl = tf.keras.optimizers.SGD(learning_rate=0.25, momentum=0.9)
loss = tf.keras.losses.mean_squared_error

In [11]:
# compile model using mse as a measure of modelSL performance

modelSL.compile(optimizer=optimsl, loss=loss, metrics = [rmse])

In [12]:
# Fitting the modelSL

modelSL.fit(X_train, y_train, epochs=1000)

- loss: 0.0509 - rmse: 0.2028
Epoch 793/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.0506 - rmse: 0.2031
Epoch 794/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.0505 - rmse: 0.2035
Epoch 795/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.0501 - rmse: 0.2017
Epoch 796/1000
4/4 [==============================] - 0s 5ms/step - loss: 0.0507 - rmse: 0.2023
Epoch 797/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.0501 - rmse: 0.2017
Epoch 798/1000
4/4 [==============================] - 0s 5ms/step - loss: 0.0509 - rmse: 0.2040
Epoch 799/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.0505 - rmse: 0.2032
Epoch 800/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0504 - rmse: 0.2026
Epoch 801/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.0509 - rmse: 0.2035
Epoch 802/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.0509 - rmse: 0.2040
Epoch 803/

In [13]:
# optimizer for 2L
optim2l = tf.keras.optimizers.SGD(learning_rate=0.55, momentum=0.65)

In [14]:
# compile model using mse as a measure of model2L performance

model2L.compile(optimizer=optim2l, loss=loss, metrics = [rmse])

In [15]:
# Fitting the model2L

model2L.fit(X_train, y_train, epochs=1000)

 - loss: 0.0515 - rmse: 0.2039
Epoch 793/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.0528 - rmse: 0.2080
Epoch 794/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0517 - rmse: 0.2038
Epoch 795/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0511 - rmse: 0.2041
Epoch 796/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.0510 - rmse: 0.2042
Epoch 797/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.0509 - rmse: 0.2030
Epoch 798/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0511 - rmse: 0.2046
Epoch 799/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.0508 - rmse: 0.2032
Epoch 800/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.0513 - rmse: 0.2045
Epoch 801/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.0509 - rmse: 0.2040
Epoch 802/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.0505 - rmse: 0.2025
Epoch 803

In [16]:
train_pred = modelSL.predict(X_train)
train_pred[:, 0]
y_train[:, 0]

array([0.42703533, 0.06912442, 0.87096774, 0.22887865, 0.41474654,
       0.0952381 , 0.38095238, 0.44086022, 0.21505376, 0.44393241,
       0.48387097, 0.61136713, 0.7265745 , 0.26420891, 0.6328725 ,
       0.53149002, 0.21658986, 0.33640553, 0.14746544, 0.83870968,
       0.12288786, 0.10445469, 0.15207373, 0.70814132, 0.21505376,
       0.66513057, 0.1797235 , 0.61443932, 0.42703533, 0.3609831 ,
       0.77265745, 0.64669739, 0.06912442, 0.67281106, 0.51766513,
       0.23041475, 0.39938556, 0.59754224, 0.04915515, 0.60061444,
       0.15668203, 0.39631336, 0.30107527, 0.22887865, 0.39016897,
       0.50384025, 0.00614439, 0.61443932, 0.15360983, 0.28725038,
       0.95238095, 0.28264209, 0.21658986, 0.29339478, 0.48387097,
       0.47619048, 0.25652842, 0.4546851 , 0.3609831 , 0.1843318 ,
       0.38095238, 0.61904762, 1.        , 0.55760369, 0.37634409,
       0.10906298, 0.37173579, 0.48387097, 0.13978495, 0.31797235,
       0.56682028, 0.23041475, 0.78187404, 0.05529954, 0.80030

In [17]:
# finding the mean

np.mean(loss(train_pred, y_train))

0.04990286016326584

In [18]:
# Etr formula to each machenical properties

def etr(actual, predicted):
    return np.mean(np.abs(actual, predicted))

In [19]:
# Summary

modelSL.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                110       
_________________________________________________________________
dropout (Dropout)            (None, 10)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 88        
_________________________________________________________________
dropout_1 (Dropout)          (None, 8)                 0         
_________________________________________________________________
dense_2 (Dense)              (None, 5)                 45        
Total params: 243
Trainable params: 243
Non-trainable params: 0
_________________________________________________________________


In [19]:
# taking one row of test dataset

X_test[0].reshape(1, -1).shape

(1, 10)

In [23]:
# Predictions

predicted = modelSL.predict(X_test[0].reshape(1, -1))
# pd.DataFrame(columns=['YS', 'UTS', 'EL', 'RA', 'IS'], data=predicted)
print(predicted)

[[0.39840516 0.38351145 0.51038504 0.6973969  0.5275403 ]]


In [45]:
# input from UI

# input = np.array([[0.32],	[0.23],	[1.28],	[0.028],	[0.85],	[0.46],	[0.16],	[38],	[38],	[580]])
input = np.array([[0.32,	0.23,	1.28,	0.028,	0.85,	0.46,	0.16,	38,	38,	580]])
print(input)

[[3.20e-01 2.30e-01 1.28e+00 2.80e-02 8.50e-01 4.60e-01 1.60e-01 3.80e+01
  3.80e+01 5.80e+02]]


In [46]:
# Scaling the input values from UI

input_scale = MinMaxScaler()

input_scaled = input_scale.fit_transform(input)
input_scaled.shape

(1, 10)

In [60]:
# prediction with input values from UI
output_predicted = modelSL.predict(input_scaled)
# pd.DataFrame(columns=['YS', 'UTS', 'EL', 'RA', 'IS'], data=output_predicted)
# print(output_predicted)
# print(output_predicted.flatten())
# print(output_predicted.ravel())

# convert list into string 
converted_list = [str(element) for element in output_predicted.flatten()]
joined_string = ",".join(converted_list)
# print(joined_string)

0.39293528,0.3775866,0.5142056,0.7017079,0.5311333


In [48]:
# convert predicted values to its original states show we can compare our model working for UI

y_scale.inverse_transform(output_predicted)
# pd.DataFrame(columns=['YS', 'UTS', 'EL', 'RA', 'IS'], data=y_scale.inverse_transform(output_predicted))

array([[798.8009 , 929.0209 ,  21.22729,  56.61234,  56.95953]],
      dtype=float32)

In [28]:
# convert predicted values to its original states show we can campare our model working

y_scale.inverse_transform(predicted)

array([[802.36176 , 932.50476 ,  21.16616 ,  56.454987,  56.675686]],
      dtype=float32)

In [29]:
# Saving the model single layer

modelSL.save_weights('modelSL.hdf5')

In [30]:
# Saving the model double layer

model2L.save_weights('model2L.hdf5')

In [31]:
# loading the model single layer

modelSL.load_weights('modelSL.hdf5')

In [32]:
# loading the model double layer

model2L.load_weights('model2L.hdf5')